name: Build and test

on: [push]

jobs:
  build-test:
    name: Build and test package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run --silent prettier-check
      - run: npm run --silent lint-check
      - run: npm run --silent build
      - run: npm test
